name: OrgWarden

on:
  schedule:
    - cron: '14 0 * * *' # run daily at 10:00 am Eastern
  workflow_dispatch: # enables manual trigger

jobs:
  Run-OrgWarden:
    runs-on: ubuntu-latest
    steps:
      - uses: gt-tech-ai/OrgWarden@v0
        with:
          org-url: https://github.com/gt-tech-ai
          github-pat: ${{ secrets.ORG_WARDEN_AUDIT_PAT }}